//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using MauiAppNet9Demo.Shared.Abstractions;
using Microsoft.AspNetCore.Components;

namespace MauiAppNet9Demo.Shared.Pages
{
    public partial class LocationComponent
    {
        [Inject]
        public ILocationServices LocationServices { get; set; }
        public LocationDTO LocationDTO { get; set; }
        string auxlocation;
        public async Task GetLocation()
        {
            var location = await LocationServices.GetCurrentLocation();
            if (location != null)
            {
                LocationDTO = location;
                auxlocation = $"https://www.google.com/maps?q={LocationDTO.Latitude.ToString().Replace(',', '.')},{LocationDTO.Longitude.ToString().Replace(',', '.')}";
            }
        }
    }
}